### ISSUE TITLE
Add 'neovim-plugin' as topic to the GitHub repository

### ISSUE THREAD

**Issue by Frestein** [supermaven-inc/supermaven-nvim#103]
I would like to request the addition of the 'neovim-plugin' tag to this repository. This tag is necessary for the plugin to be listed on [dotfyle.com](https://dotfyle.com/), which is a valuable resource for Neovim users.

Please consider tagging the repository accordingly.

![image](https://github.com/user-attachments/assets/7c60f2c2-3a8c-4246-8aca-e0befb0386f7)

**Comment by sm-victorw** [comment]
The tag has been added now

**Comment by Frestein** [comment]
> The tag has been added now

Thank you!
https://dotfyle.com/plugins/supermaven-inc/supermaven-nvim
