### ISSUE TITLE
Add support for Linux primary selection (copy&paste) in PyCharm plugin

### ISSUE THREAD

**Issue by makkus** [supermaven-inc/supermaven-nvim#107]
Heya, this throws me every time, even though I've been using Supermaven happily for quite a while now: 

In contrast to how basically everything else works in PyCharm, when I make a selection in the Supermaven chat window I can't just paste it with the middle mouse button into any destination, I have to manually copy & paste using the clipboard selection.

It would be great if Supermaven would align with the default OS selection type(s).

**Comment by devenv** [comment]
it's the vim plugin repo

**Comment by makkus** [comment]
Ups, sorry 🙄
