### ISSUE TITLE
Error when navigating to beyond certain lines (content size?) in a larger file eg. as long as my cursor is on line 139 or later in one of my files.

### ISSUE THREAD

**Issue by hboon** [supermaven-inc/supermaven-nvim#11]
I get this with any move, like G, h, j, k, l, 140G, etc:

> Error detected while processing CursorMoved Autocommands for "*":
> Error executing lua callback: .../paqs/start/supermaven-nvim/lua/supermaven-nvim/util.lua:164: string slice too long
> stack traceback:
>         [C]: in function 'byte'
>         .../paqs/start/supermaven-nvim/lua/supermaven-nvim/util.lua:164: in function 'get_utf8_length'
>         ...maven-nvim/lua/supermaven-nvim/binary/binary_handler.lua:74: in function 'on_update'
>         ...upermaven-nvim/lua/supermaven-nvim/document_listener.lua:23: in function <...upermaven-nvim/lua/supermaven-nvim/document_listener.lua:17>

**Comment by Hashiraee** [comment]
This is fixed in PR #7 and is already reviewed/approved, only needs to be merged.
