### ISSUE TITLE
Activation popup opens every time I enter nvim and I don't know how to supress it

### ISSUE THREAD

**Issue by tjazerzen** [supermaven-inc/supermaven-nvim#114]
I'm using free version of supermaven. This is my current config (I'm using `lazy.nvim`):

```lua
{
	"supermaven-inc/supermaven-nvim",
	config = function()
		require("supermaven-nvim").setup({
			log_level = "off",
		})
		require("supermaven-nvim.api").use_free_version()
	end,
}
```

whenever I enter neovim, I get a popup window saying `Please visit the following URL to set up Supermaven Pro (or use :SupermavenUseFree).`. Is it possible to suppress that?

![image](https://github.com/user-attachments/assets/886a35b3-485b-435e-9a5d-e944d6529354)

**Comment by sm-victorw** [comment]
I think this is just a result of calling `require("supermaven-nvim.api").use_free_version()` in the config. Is there any reason this needs to be run on every startup? If removed does this message no longer appear?

**Comment by youssef-lr** [comment]
This plugin is unusable for me, I can't get past that popup and can't use the free trial to evaluate if I want to purchase the pro subscription.

Edit: it just started working fine for me.

**Comment by tjazerzen** [comment]
@sm-victorw I removed `require("supermaven-nvim.api").use_free_version()` and it works - previously this line was required but after the version update this works. Thank you!
