### ISSUE TITLE
Programmatically accept suggestion

### ISSUE THREAD

**Issue by sQVe** [supermaven-inc/supermaven-nvim#15]
Hey,

I would love to be able to interact with this plugin via Lua code. This is super useful when configuring AI suggestions together with LSP completion.

This is how I set up accepting both Luasnip snippets and [GitHub Copilot ](https://github.com/zbirenbaum/copilot.lua) under the save key via [`nvim-cmp`](https://github.com/hrsh7th/nvim-cmp):

```lua
M.expand = function(fallback)
  local luasnip = require('luasnip')
  local suggestion = require('copilot.suggestion')

  if luasnip.expandable() then
    luasnip.expand()
  elseif suggestion.is_visible() then
    suggestion.accept()
  else
    fallback()
  end
end
```

Cheers!

**Comment by hboon** [comment]
Second this. I think it just mapping <Tab> to a function like this, but falling back to <Tab> worked for me yesterday, but it no longer works.

**Comment by kaiiserni** [comment]
As of the last PR, something like this should work btw:

```lua
require("supermaven-nvim").setup({
  disable_keymaps = true
})

...

M.expand = function(fallback)
  local luasnip = require('luasnip')
  local suggestion = require('supermaven-nvim.completion_preview')

  if luasnip.expandable() then
    luasnip.expand()
  elseif suggestion.has_suggestion() then
    suggestion.on_accept_suggestion()
  else
    fallback()
  end
end 
```

**Comment by hboon** [comment]
Just in case this saves someone's time in the future, there is also `expand_or_jumpable()` and `expand_or_jump()`.

**Comment by sQVe** [comment]
Closing issue since https://github.com/supermaven-inc/supermaven-nvim/issues/15#issuecomment-2119390970 provides a solution.
