### ISSUE TITLE
String slice too long [on util.lua:164]

### ISSUE THREAD

**Issue by mariesco** [supermaven-inc/supermaven-nvim#17]
I get the following error randomly on my project

<img width="1429" alt="Captura de pantalla 2024-05-13 a la(s) 7 28 25 p  m" src="https://github.com/supermaven-inc/supermaven-nvim/assets/28025660/5db0f376-ff8d-4fbd-a701-cb8220f25e4d">

**Comment by victorw-xyz** [comment]
This was a bug that I believe was fixed in #7, can you update the plugin and see if this happens again?

**Comment by mariesco** [comment]
> This was a bug that I believe was fixed in #7, can you update the plugin and see if this happens again?

I was creating a PR fixing the get_utf8_length function, but I don't have permissions... Now I update and test. What was the problem?

**Comment by mariesco** [comment]
@victorw-xyz  I don't have the problem anymore...If you could give me a link to see the commit where it was solved and understand it, I would appreciate it.

I would also like to know how I can get permissions to create PRs and be able to contribute. Thank you so much!

**Comment by victorw-xyz** [comment]
@mariesco The problem was that we were using the str.byte function which did not work for large strings.

You can fork the repository and after committing changes to the fork, make a pull request from the fork. I guess we should include a guide for contributing, so it is more clear.
