### ISSUE TITLE
"Could not find activation URL" when using ":SupermavenUsePro"

### ISSUE THREAD

**Issue by w1png** [supermaven-inc/supermaven-nvim#39]
Hello, I started a Pro trial and when I run SupermavenUsePro I get this error:
<img width="2549" alt="image" src="https://github.com/supermaven-inc/supermaven-nvim/assets/74238629/85b3bbec-8ce7-4ae4-beed-1008f865a2c4">

**Comment by ian-vu** [comment]
@w1png I got this as well. Seems like the flow is to run `SupermavenLogout` first and then run `SupermavenUsePro` after. 

This flow seems like it could use some work as it is not clear without reading the docs.

Hope this helps.

**Comment by w1png** [comment]
> @w1png I got this as well. Seems like the flow is to run `SupermavenLogout` first and then run `SupermavenUsePro` after. 
> 
> 
> 
> This flow seems like it could use some work as it is not clear without reading the docs.
> 
> 
> 
> Hope this helps. 

That worked. Thanks!
