### ISSUE TITLE
Possible to suppress log "Supermaven Pro is running." when loading?

### ISSUE THREAD

**Issue by ian-vu** [supermaven-inc/supermaven-nvim#42]
Would there be any way to suppress the log `Supermaven Pro is running.` when loading up the plugin?

**Comment by AlejandroSuero** [comment]
PR #27 solves this problem along with issue #4

**Comment by joaomendoncaa** [comment]
> PR #27 solves this problem along with issue #4

Awesome! I supose you're from the team. Any expectations on when this gets merged?

**Comment by AlejandroSuero** [comment]
@joaomendoncaa not from the team, so I am not sure. I am just a guy who likes to help and have a lot of free time at the moment 😅

**Comment by joaomendoncaa** [comment]
> @joaomendoncaa not from the team, so I am not sure. I am just a guy who likes to help and have a lot of free time at the moment 😅

![image](https://github.com/supermaven-inc/supermaven-nvim/assets/57664150/20950bd6-2ae8-4289-b641-ff0a09851e5e)

This is genuinely annoying! 😄 I'm about to fork your PRs and install them instead of the original plugin just because of it.

**Comment by HakonHarnes** [comment]
Would also like to see this issue resolved!
