### ISSUE TITLE
[Suggestion] ignoring files (not filetypes) dynamically

### ISSUE THREAD

**Issue by ahmedelgabri** [supermaven-inc/supermaven-nvim#57]
`ignore_filetypes` currently is limited to filetypes, but in some cases, I want to disable the plugin from running on some specific files. For example, some shellscript files that contains some secrets, token, etc… 

If I add `bash = true` in `ignore_filetypes` then this will disable it for all bash files. I don't want this. I want to be able to do something like this instead

```lua
function()
   return string.match(vim.fn.expand('%:t'), 'foo.sh') != nil
end

**Comment by AlejandroSuero** [comment]
I usually use `_private` or `.private`, so for me it would be useful as well, currently I am doing it in my nvim-config to not load selected plugins.

I think a good guy to resolve this cases would be with something like [none-ls.nvim](https://github.com/nvimtools/none-ls.nvim) in the [utils file](https://github.com/nvimtools/none-ls.nvim/blob/8691504118b252d64fc5023a104aedd100ab754a/lua/null-ls/utils/init.lua#L99-L140), this is useful with `none-ls` for example to not use `luacheck` if `selene.toml` is in the root. In supermaven's case checking for root wouldn't be necessary.

Creating a `condition` entry on the plugin's config like this (rough concept):

```lua
local files = {
  { ft = { "bash", "javascript", ... }, ignore = { "foo", "_private", ".private", ... },
  ...
}

require("supermaven-nvim").setup({
  -- condition would need to return a boolean
  condition = function(util)
    return util.file_matches(files)
  end,
})

---@class FilesToMatch
---@field ft string? | string[]?
---@field ignore string | string[]

---@param files FilesToMatch[]
---@return boolean
util.file_matches = function(files)
  -- check if `files.ft` is specified, if not just check filename with `files.match`
    -- check current filetype within or some of `files.ft`
      -- check current filename contains or some of `files.ignore`
end
```

> [!NOTE]
> This could be more user friendly with **more thought** into it and some **feedback**.

**Comment by ahmedelgabri** [comment]
Looks good. But I'd personally start with just adding an option that takes a function that returns a Boolean without the utils. And leave the logic for the consumer. _if_ later there is a demand for such utils you can add it.

**Comment by AlejandroSuero** [comment]
That is a great idea, a nice place to start. Thanks for the feedback.

**Comment by AlejandroSuero** [comment]
@ahmedelgabri I made this quick demo and added this to my config:

```lua
require("supermaven-nvim").setup({
  condition = function()
    return vim.fn.expand(":t:r") ~= "api"
  end
})
```

I am thinking if its better to default condition to `false`, and check if condition is true to stop. Right now its defaulting to `true`.

https://github.com/supermaven-inc/supermaven-nvim/assets/71392160/90931945-4fe4-4f10-ad50-802db97c7310

**Comment by ahmedelgabri** [comment]
> I am thinking if its better to default condition to `false`, and check if condition is true to stop. Right now its defaulting to `true`.

Agree, the default should be `false`, `true` should mean disable the plugin.

**Comment by AlejandroSuero** [comment]
@ahmedelgabri I made the changes in the PR above if you want to try them out.
