### ISSUE TITLE
bug: creates `.supermaven/config.json` on every startup

### ISSUE THREAD

**Issue by aarondill** [supermaven-inc/supermaven-nvim#74]
Recently, this plugin has begun creating `./.supermaven/config.json` if it doesn't exist (relative to CWD).
It also forces the user to call `:SupermavenUseFree` each time this file is created, rather than creating/using `~/.supermaven/config.json`.
Note that downloaded binaries are still stored in `~/.supermaven/config.json`.

I suspect this is an upstream problem (with `sm-agent`), however there's no available bug tracker for the upstream.

**Comment by jvanja** [comment]
I can confirm this bug. It started happening after the latest plugin update.

**Comment by jsnanigans** [comment]
same here, I almost pushed the config.json to my public repo.
I get that it might be useful to have a config for each project, but maybe let us set a default path to the plugin config that it can use if there is none in the project directory. and dont force it

**Comment by soeguet** [comment]
This just made me disable the plugin. It is way too disruptive and caused quite some work

**Comment by jsnanigans** [comment]
Maybe this can help others, until this is fixed, you can define the exact version of the plugin. If you are also using Lazy, then add this specific version from the commit before `SM_EDITOR = "neovim"` was set:
```lua
  {
    'supermaven-inc/supermaven-nvim',
    commit = 'df3ecf7',
    config = function()
      require('supermaven-nvim').setup {
```

**Comment by Redoxahmii** [comment]
Same bug almost committed it to repo and this prompts for me in every folder i open.

**Comment by pkdevel** [comment]
also your aggressive popup, reminding me of this issue whenever i open nvim in a new folder 👎 
its not only pissing me off, there's also no need to constantly force open that popup.
you might want to consider changing that behaviour

**Comment by aarondill** [comment]
> Maybe this can help others, until this is fixed, you can define the exact version of the plugin. If you are also using Lazy, then add this specific version from the commit before `SM_EDITOR = "neovim"` was set:
> 
> ```lua
>   {
>     'supermaven-inc/supermaven-nvim',
>     commit = 'df3ecf7',
>     config = function()
>       require('supermaven-nvim').setup {
> ```

@jsnanigans I tried that, but it doesn't seem to work for me. That's why I suspect this was changed in `sm-agent`, rather than the `nvim` plugin directly.

**Comment by mirsella** [comment]
@aarondill works for me, make sure to update the plugin, maybe delete the install folder and reinstall.
the commit which fix it for most of us (https://github.com/supermaven-inc/supermaven-nvim/commit/c5bb0490bdfc36a7841e5b82c8f6b92b5b8beef3) just pass a new environment variable to sm-agent, so indeed it's probably that

**Comment by Z1NGOD** [comment]
@aarondill Hey mate, could you please tell me what you did to fix the issue? I updated the plugin but it still wants to log in or tell me to use the free version.

**Comment by pankajgarkoti** [comment]
just running Lazy update works too

*Pankaj Garkoti, CTO @ Mavex.ai <http://Mavex.ai>*

**Comment by Acero-AD** [comment]
I still have this issue

**Comment by abenz1267** [comment]
the faulty commit has been reverted.

**Comment by aarondill** [comment]
Closing thanks to d71257f
