### ISSUE TITLE
Getting suggestion in new lines before typing anything

### ISSUE THREAD

**Issue by amirhhashemi** [supermaven-inc/supermaven-nvim#8]
Sometimes I get suggestion while I haven't typed anything (in a new line).

![image](https://github.com/supermaven-inc/supermaven-nvim/assets/87268103/049d684b-2352-49ff-a0cd-f3a0462fe518)

I find it a little annoying. I would like to get suggestion only when I type at least one character. I think that should be the default behavior. All code completion tools I've worked with wait for me to type one or two character and then give me a suggestion based on that.

I can think of situations where this behaviour could be useful. Like when I have a function that is not defined and Supermaven can help me define it before I type anything. But in other situations I find it annoying. Unfortunately I get a lot of unuseful suggestions in new lines.

Please consider changing this behaviour or at least provide an option to configure it.

**Comment by AlejandroSuero** [comment]
@amirhhashemi, with the addition of `cmp` support by @kaiiserni in #28, you can use [nvim-cmp](https://github.com/hrsh7th/nvim-cmp) to only give you suggestions after typing. So maybe this solves your problem.

> [!NOTE]
>
> The way to set it up it explained [in this section of the `README.md`](https://github.com/supermaven-inc/supermaven-nvim?tab=readme-ov-file#using-with-nvim-cmp).

**Comment by amirhhashemi** [comment]
Ok, thanks. I will try it later. I close the issue for now.
