### ISSUE TITLE
activation link works but neovim plugin still thinks not activated

### ISSUE THREAD

**Issue by rbutera** [supermaven-inc/supermaven-nvim#86]
as per title, I've tried running :SupermavenLogout and then :SupermavenUsePro, the same link as last time is generated, I go to the website and click the connect button, and unlike usual supermaven in neovim doesn't update with the pro status. I have a paid subscription

**Comment by sm-victorw** [comment]
I tried reproducing this, but was unable to. In your `$HOME/.supermaven` directory, there should be a `config.json` file that is created, is that file present? And if so, does it contain an API key, or just a link id?

**Comment by rbutera** [comment]
the api_key field doesn't get updated, and `accepted_free_version` stays as `true`

**Comment by rbutera** [comment]
I've tried removing the .supermaven directory and clean (re)installing.

At this point I'm losing productivity over this, is there any way I can just get an api key from the website?

**Comment by rbutera** [comment]
here's my most recent activate link: https://supermaven.com/activate-extension?linkId=fV6E7IDTmpKJEP6qTTLoclJxqNpIdR4u

**Comment by sm-victorw** [comment]
Could you create a file called `sm-log.txt` in your home directory, and let me know what it reads when you try to activate the extension? Normally we would expect to see `API key response message: The API key has been generated and is ready to be used.` and `Obtained API key, saving to config` in the `sm-log.txt` but my guess is that something is preventing it from being saved into the config file

**Comment by rbutera** [comment]
I'm not sure if it's at all related to my Neovim config, because Supermaven works fine on my other machine(s) (and even in vscode). In case you think it might be, here's my config:

https://github.com/rbutera/astronvim_config

and I'm currently using:

```
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1723675123
```

**Comment by sm-victorw** [comment]
The vscode extension reads the same config that the Neovim plugin reads, if vscode has generated an api key the Neovim plugin should already be reading from it, when you say vscode works, you mean on this same machine?

Regarding the other machine(s), are those other machine(s) using the same Neovim configuration? I don't think this is related to Neovim, the log you posted seems to suggest something going wrong with either the `sm-agent` or the website/endpoint.

**Comment by rbutera** [comment]
ah i just assumed vscode was working but i hadn't installed it yet. I copied my config.json from the other OS i have on this machine and it's all working fine. So yeah I think there is an issue with the `sm-agent` or the endpoint so perhaps best to close this issue and flag it to the people responsible for maintaining either of those.
